import { db } from "./db";
import { foods } from "../schema";
import { sql } from "drizzle-orm";

const ayurvedicFoods = [
  {
    name: "Basmati Rice",
    nameHindi: "Basmati Chawal",
    rasa: ["Sweet"],
    virya: "Cooling",
    vipaka: "Sweet",
    doshaEffects: { vata: "decreases", pitta: "decreases", kapha: "increases" },
    foodCategory: "grains",
    cuisineType: "Indian",
    nutritionalData: { calories: 130, protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "cup cooked", grams: 158 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["boiled", "steamed"],
    preparationTime: 25,
    isVegetarian: true,
  },
  {
    name: "Moong Dal",
    nameHindi: "Moong Ki Daal",
    rasa: ["Sweet", "Astringent"],
    virya: "Cooling",
    vipaka: "Sweet",
    doshaEffects: { vata: "decreases", pitta: "decreases", kapha: "neutral" },
    foodCategory: "legumes",
    cuisineType: "Indian",
    nutritionalData: { calories: 105, protein: 7, carbs: 18.3, fat: 0.4, fiber: 7.6, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "cup cooked", grams: 200 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["boiled", "pressure_cooked"],
    preparationTime: 30,
    isVegetarian: true,
  },
  {
    name: "Ghee",
    nameHindi: "Desi Ghee",
    rasa: ["Sweet"],
    virya: "Cooling",
    vipaka: "Sweet",
    prabhava: "Enhances digestion (Agni deepana)",
    doshaEffects: { vata: "decreases", pitta: "decreases", kapha: "increases" },
    foodCategory: "fats",
    cuisineType: "Indian",
    nutritionalData: { calories: 112, protein: 0, carbs: 0, fat: 12.7, fiber: 0, vitamins: { A: 108 }, minerals: {} },
    servingSizes: [{ name: "tablespoon", grams: 14 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["raw", "cooking_medium"],
    preparationTime: 0,
    isVegetarian: true,
  },
  {
    name: "Turmeric",
    nameHindi: "Haldi",
    rasa: ["Bitter", "Pungent", "Astringent"],
    virya: "Heating",
    vipaka: "Pungent",
    prabhava: "Anti-inflammatory, blood purifier",
    doshaEffects: { vata: "decreases", pitta: "neutral", kapha: "decreases" },
    foodCategory: "spices",
    cuisineType: "Indian",
    nutritionalData: { calories: 9, protein: 0.3, carbs: 2, fat: 0.1, fiber: 0.7, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "teaspoon", grams: 3 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["raw", "cooked"],
    preparationTime: 0,
    isVegetarian: true,
  },
  {
    name: "Ginger",
    nameHindi: "Adrak",
    rasa: ["Pungent"],
    virya: "Heating",
    vipaka: "Sweet",
    prabhava: "Universal medicine (Vishwabheshaja)",
    doshaEffects: { vata: "decreases", pitta: "increases", kapha: "decreases" },
    foodCategory: "spices",
    cuisineType: "Indian",
    nutritionalData: { calories: 5, protein: 0.1, carbs: 1.1, fat: 0, fiber: 0.1, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "tablespoon grated", grams: 6 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["raw", "boiled", "cooked"],
    preparationTime: 0,
    isVegetarian: true,
  },
  {
    name: "Amla (Indian Gooseberry)",
    nameHindi: "Amla",
    rasa: ["Sour", "Sweet", "Astringent", "Bitter", "Pungent"],
    virya: "Cooling",
    vipaka: "Sweet",
    prabhava: "Richest source of Vitamin C, Rasayana (rejuvenator)",
    doshaEffects: { vata: "decreases", pitta: "decreases", kapha: "decreases" },
    foodCategory: "fruits",
    cuisineType: "Indian",
    nutritionalData: { calories: 44, protein: 0.9, carbs: 10.2, fat: 0.6, fiber: 4.3, vitamins: { C: 600 }, minerals: {} },
    servingSizes: [{ name: "piece", grams: 50 }],
    seasonalAvailability: ["winter"],
    cookingMethods: ["raw", "pickled", "dried"],
    preparationTime: 0,
    isVegetarian: true,
  },
  {
    name: "Cumin Seeds",
    nameHindi: "Jeera",
    rasa: ["Pungent"],
    virya: "Cooling",
    vipaka: "Pungent",
    prabhava: "Digestive stimulant",
    doshaEffects: { vata: "decreases", pitta: "neutral", kapha: "decreases" },
    foodCategory: "spices",
    cuisineType: "Indian",
    nutritionalData: { calories: 8, protein: 0.4, carbs: 0.9, fat: 0.5, fiber: 0.2, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "teaspoon", grams: 2 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["tempered", "dry_roasted", "powdered"],
    preparationTime: 0,
    isVegetarian: true,
  },
  {
    name: "Coriander Leaves",
    nameHindi: "Dhaniya Patta",
    rasa: ["Astringent", "Pungent"],
    virya: "Cooling",
    vipaka: "Sweet",
    doshaEffects: { vata: "neutral", pitta: "decreases", kapha: "neutral" },
    foodCategory: "herbs",
    cuisineType: "Indian",
    nutritionalData: { calories: 5, protein: 0.4, carbs: 0.7, fat: 0.1, fiber: 0.5, vitamins: { A: 135, C: 5 }, minerals: {} },
    servingSizes: [{ name: "tablespoon chopped", grams: 5 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["raw", "garnish"],
    preparationTime: 0,
    isVegetarian: true,
  },
  {
    name: "Bottle Gourd",
    nameHindi: "Lauki",
    rasa: ["Sweet"],
    virya: "Cooling",
    vipaka: "Sweet",
    doshaEffects: { vata: "neutral", pitta: "decreases", kapha: "neutral" },
    foodCategory: "vegetables",
    cuisineType: "Indian",
    nutritionalData: { calories: 15, protein: 0.6, carbs: 3.4, fat: 0, fiber: 0.5, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "cup chopped", grams: 116 }],
    seasonalAvailability: ["summer", "monsoon"],
    cookingMethods: ["boiled", "sauteed", "curry"],
    preparationTime: 20,
    isVegetarian: true,
  },
  {
    name: "Ashwagandha Milk",
    nameHindi: "Ashwagandha Doodh",
    rasa: ["Sweet", "Bitter", "Astringent"],
    virya: "Heating",
    vipaka: "Sweet",
    prabhava: "Adaptogenic, strengthening, Rasayana",
    doshaEffects: { vata: "decreases", pitta: "neutral", kapha: "decreases" },
    foodCategory: "beverages",
    cuisineType: "Indian",
    nutritionalData: { calories: 80, protein: 3.4, carbs: 5, fat: 4, fiber: 0, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "cup", grams: 240 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["boiled"],
    preparationTime: 10,
    isVegetarian: true,
  },
  {
    name: "Bitter Gourd",
    nameHindi: "Karela",
    rasa: ["Bitter"],
    virya: "Cooling",
    vipaka: "Pungent",
    prabhava: "Blood sugar regulation",
    doshaEffects: { vata: "increases", pitta: "decreases", kapha: "decreases" },
    foodCategory: "vegetables",
    cuisineType: "Indian",
    nutritionalData: { calories: 17, protein: 1, carbs: 3.7, fat: 0.2, fiber: 2.8, vitamins: { C: 84 }, minerals: {} },
    servingSizes: [{ name: "cup sliced", grams: 93 }],
    seasonalAvailability: ["summer", "monsoon"],
    cookingMethods: ["sauteed", "stuffed", "fried"],
    preparationTime: 25,
    isVegetarian: true,
  },
  {
    name: "Roti (Whole Wheat)",
    nameHindi: "Roti",
    rasa: ["Sweet"],
    virya: "Neutral",
    vipaka: "Sweet",
    doshaEffects: { vata: "decreases", pitta: "neutral", kapha: "increases" },
    foodCategory: "grains",
    cuisineType: "Indian",
    nutritionalData: { calories: 71, protein: 3, carbs: 15, fat: 0.4, fiber: 2, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "piece", grams: 30 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["dry_roasted"],
    preparationTime: 15,
    isVegetarian: true,
  },
  {
    name: "Yogurt (Curd)",
    nameHindi: "Dahi",
    rasa: ["Sour", "Sweet"],
    virya: "Cooling",
    vipaka: "Sour",
    doshaEffects: { vata: "decreases", pitta: "increases", kapha: "increases" },
    foodCategory: "dairy",
    cuisineType: "Indian",
    nutritionalData: { calories: 61, protein: 3.5, carbs: 4.7, fat: 3.3, fiber: 0, vitamins: {}, minerals: { calcium: 121 } },
    servingSizes: [{ name: "cup", grams: 150 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["raw", "raita"],
    preparationTime: 0,
    isVegetarian: true,
  },
  {
    name: "Spinach",
    nameHindi: "Palak",
    rasa: ["Astringent", "Sweet"],
    virya: "Cooling",
    vipaka: "Pungent",
    doshaEffects: { vata: "increases", pitta: "decreases", kapha: "decreases" },
    foodCategory: "vegetables",
    cuisineType: "Indian",
    nutritionalData: { calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, vitamins: { A: 469, C: 28, K: 483 }, minerals: { iron: 2.7 } },
    servingSizes: [{ name: "cup raw", grams: 30 }],
    seasonalAvailability: ["winter", "spring"],
    cookingMethods: ["sauteed", "boiled", "pureed"],
    preparationTime: 15,
    isVegetarian: true,
  },
  {
    name: "Fennel Seeds",
    nameHindi: "Saunf",
    rasa: ["Sweet", "Pungent"],
    virya: "Cooling",
    vipaka: "Sweet",
    prabhava: "Digestive, carminative",
    doshaEffects: { vata: "decreases", pitta: "decreases", kapha: "decreases" },
    foodCategory: "spices",
    cuisineType: "Indian",
    nutritionalData: { calories: 7, protein: 0.3, carbs: 1, fat: 0.3, fiber: 0.8, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "teaspoon", grams: 2 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["raw", "dry_roasted"],
    preparationTime: 0,
    isVegetarian: true,
  },
  {
    name: "Pomegranate",
    nameHindi: "Anar",
    rasa: ["Sweet", "Astringent", "Sour"],
    virya: "Neutral",
    vipaka: "Sweet",
    prabhava: "Blood builder, heart tonic",
    doshaEffects: { vata: "decreases", pitta: "decreases", kapha: "neutral" },
    foodCategory: "fruits",
    cuisineType: "Indian",
    nutritionalData: { calories: 83, protein: 1.7, carbs: 18.7, fat: 1.2, fiber: 4, vitamins: { C: 10 }, minerals: { potassium: 236 } },
    servingSizes: [{ name: "cup seeds", grams: 174 }],
    seasonalAvailability: ["autumn", "winter"],
    cookingMethods: ["raw"],
    preparationTime: 5,
    isVegetarian: true,
  },
  {
    name: "Coconut",
    nameHindi: "Nariyal",
    rasa: ["Sweet"],
    virya: "Cooling",
    vipaka: "Sweet",
    doshaEffects: { vata: "decreases", pitta: "decreases", kapha: "increases" },
    foodCategory: "fruits",
    cuisineType: "Indian",
    nutritionalData: { calories: 354, protein: 3.3, carbs: 15.2, fat: 33.5, fiber: 9, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "cup shredded", grams: 80 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["raw", "grated", "milk"],
    preparationTime: 5,
    isVegetarian: true,
  },
  {
    name: "Toor Dal (Pigeon Pea)",
    nameHindi: "Arhar Ki Daal",
    rasa: ["Sweet", "Astringent"],
    virya: "Heating",
    vipaka: "Sweet",
    doshaEffects: { vata: "decreases", pitta: "neutral", kapha: "neutral" },
    foodCategory: "legumes",
    cuisineType: "Indian",
    nutritionalData: { calories: 118, protein: 7.5, carbs: 20, fat: 0.4, fiber: 5, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "cup cooked", grams: 200 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["pressure_cooked", "boiled"],
    preparationTime: 35,
    isVegetarian: true,
  },
  {
    name: "Banana",
    nameHindi: "Kela",
    rasa: ["Sweet"],
    virya: "Cooling",
    vipaka: "Sour",
    doshaEffects: { vata: "decreases", pitta: "neutral", kapha: "increases" },
    foodCategory: "fruits",
    cuisineType: "Indian",
    nutritionalData: { calories: 89, protein: 1.1, carbs: 22.8, fat: 0.3, fiber: 2.6, vitamins: { B6: 0.4, C: 9 }, minerals: { potassium: 358 } },
    servingSizes: [{ name: "medium", grams: 118 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["raw"],
    preparationTime: 0,
    isVegetarian: true,
  },
  {
    name: "Almonds",
    nameHindi: "Badam",
    rasa: ["Sweet"],
    virya: "Heating",
    vipaka: "Sweet",
    prabhava: "Brain tonic, Medhya Rasayana",
    doshaEffects: { vata: "decreases", pitta: "increases", kapha: "increases" },
    foodCategory: "nuts",
    cuisineType: "Indian",
    nutritionalData: { calories: 164, protein: 6, carbs: 6.1, fat: 14.2, fiber: 3.5, vitamins: { E: 7.3 }, minerals: { magnesium: 76 } },
    servingSizes: [{ name: "handful", grams: 28 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["soaked", "raw"],
    preparationTime: 0,
    isVegetarian: true,
  },
  {
    name: "Khichdi",
    nameHindi: "Khichdi",
    rasa: ["Sweet"],
    virya: "Neutral",
    vipaka: "Sweet",
    prabhava: "Easiest to digest, Sattvic food",
    doshaEffects: { vata: "decreases", pitta: "decreases", kapha: "neutral" },
    foodCategory: "prepared",
    cuisineType: "Indian",
    nutritionalData: { calories: 150, protein: 5, carbs: 28, fat: 2, fiber: 3, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "cup", grams: 250 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["pressure_cooked"],
    preparationTime: 25,
    isVegetarian: true,
  },
  {
    name: "Tulsi (Holy Basil) Tea",
    nameHindi: "Tulsi Chai",
    rasa: ["Pungent", "Bitter"],
    virya: "Heating",
    vipaka: "Pungent",
    prabhava: "Adaptogenic, immune booster",
    doshaEffects: { vata: "decreases", pitta: "neutral", kapha: "decreases" },
    foodCategory: "beverages",
    cuisineType: "Indian",
    nutritionalData: { calories: 2, protein: 0, carbs: 0.5, fat: 0, fiber: 0, vitamins: {}, minerals: {} },
    servingSizes: [{ name: "cup", grams: 240 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["brewed"],
    preparationTime: 5,
    isVegetarian: true,
  },
  {
    name: "Jaggery",
    nameHindi: "Gud",
    rasa: ["Sweet"],
    virya: "Heating",
    vipaka: "Sweet",
    prabhava: "Iron-rich, blood purifier",
    doshaEffects: { vata: "decreases", pitta: "neutral", kapha: "increases" },
    foodCategory: "sweeteners",
    cuisineType: "Indian",
    nutritionalData: { calories: 38, protein: 0.1, carbs: 9.8, fat: 0, fiber: 0, vitamins: {}, minerals: { iron: 0.3, calcium: 8 } },
    servingSizes: [{ name: "tablespoon", grams: 10 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["raw", "dissolved"],
    preparationTime: 0,
    isVegetarian: true,
  },
  {
    name: "Triphala",
    nameHindi: "Triphala",
    rasa: ["Sweet", "Sour", "Pungent", "Bitter", "Astringent"],
    virya: "Neutral",
    vipaka: "Sweet",
    prabhava: "Contains all 5 tastes except salty. Supreme Rasayana, gut cleanser",
    doshaEffects: { vata: "decreases", pitta: "decreases", kapha: "decreases" },
    foodCategory: "supplements",
    cuisineType: "Indian",
    nutritionalData: { calories: 5, protein: 0, carbs: 1, fat: 0, fiber: 0.5, vitamins: { C: 30 }, minerals: {} },
    servingSizes: [{ name: "teaspoon powder", grams: 5 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["dissolved_in_water"],
    preparationTime: 2,
    isVegetarian: true,
  },
  {
    name: "Mung Bean Sprouts",
    nameHindi: "Ankurit Moong",
    rasa: ["Sweet", "Astringent"],
    virya: "Cooling",
    vipaka: "Sweet",
    doshaEffects: { vata: "neutral", pitta: "decreases", kapha: "decreases" },
    foodCategory: "legumes",
    cuisineType: "Indian",
    nutritionalData: { calories: 31, protein: 3.2, carbs: 6.2, fat: 0.2, fiber: 1.8, vitamins: { C: 13 }, minerals: {} },
    servingSizes: [{ name: "cup", grams: 104 }],
    seasonalAvailability: ["all_seasons"],
    cookingMethods: ["raw", "sauteed", "steamed"],
    preparationTime: 5,
    isVegetarian: true,
  },
];

export async function seedFoods() {
  const existing = await db.select({ id: foods.id }).from(foods).limit(1);
  if (existing.length > 0) return;

  console.log("Seeding Ayurvedic food database...");
  for (const food of ayurvedicFoods) {
    await db.insert(foods).values(food as any);
  }
  console.log(`Seeded ${ayurvedicFoods.length} Ayurvedic foods`);
}
